fix: fixed error: ‘class v8::Object’ has no member named 'CreationContext' (#44)
* fix: fixed error: ‘class v8::Object’ has no member named ‘CreationContext’; allowing node-gyp to rebind with node-postal, which enables node-postal to be used on Node v20.5.0

* feat: add node v16 and v20 to github actions matrix

* fix: updated workflow script to run on push and pull request events

* fix: updated actions/checkout@v2 to v3 as the former was deprecated

* test: trying to get the bindings file made/located correctly

* fix: removed incorrect cd step

* feat: added fail-fast so jobs will continue running after a node version test fails in the matrix

* feat/test: set the context depending on the node version; node v16+ use new update, else use old way

* fix/test:  added node version header to expand.cc and parser.cc

* test: changed node_version header to node header

* fix: reverting back to state where node 16,18,20 tests worked...

* fix/test: reverted github actions to v2 from v3...

* test: attempt to get tests to pass for node v16+

* fix: re-added line in ParseAddress that had been incorrectly removed

* fix: depending on node version call the right context function

* fix: removed typo